_target_: hyperbox.mutator.EnasMutator
lstm_size: 61
lstm_num_layers: 1
tanh_constant: 1.5
cell_exit_extra_step: False
skip_target: 0.4
branch_bias: 0.25
arch_loss_weight: 0.02 # 0.002:small 0.02:medium 0.2:big
reward_weight: 50
temperature: 2
entropy_reduction: 'sum' # 'sum', 'mean',
