_target_: hyperbox.models.darts_model.DARTSModel

defaults:
    - network_cfg: finegrained_resnet
    - mutator_cfg: darts_mutator
    - optimizer_cfg: adam
    - metric_cfg: accuracy
    - loss_cfg: cross_entropy
