_target_: hyperbox.models.random_model.RandomModel

defaults:
    - network_cfg: darts_network 
    - mutator_cfg: random_mutator
    - optimizer_cfg: adam
    - metric_cfg: accuracy
    - loss_cfg: cross_entropy
