_target_: hyperbox_app.medmnist.models.darts_model.DARTSModel

defaults:
    - network_cfg: da_mobile3dnet
    - mutator_cfg: onehot_mutator
    - optimizer_cfg: adam
    - metric_cfg: accuracy
    - loss_cfg: cross_entropy
    - scheduler_cfg: null