_target_: hyperbox_app.medmnist.networks.mobile3d_net.DAMobile3DNet
in_channels: 1
width_stages: [24,40,80,96,192,320]
n_cell_stages: [4,4,4,4,4,1]
stride_stages: [2,2,2,1,2,1]
width_mult: 1
num_classes: 3
dropout_rate: 0
bn_param: [0.1,1e-3]
rotate_degree: 30
crop_size: 
  - [28,28,28]
affine_degree: 0
affine_scale: [1.1,0.5]
affine_shears: 10
mask: null