_target_: hyperbox_app.medmnist.networks.mobile3d_net.DAMobile3DNet
in_channels: 1
width_stages: [24,40,80,96,192,320]
n_cell_stages: [4,4,4,4,4,1]
stride_stages: [2,2,2,2,2,2]
width_mult: 1
num_classes: 3
dropout_rate: 0
bn_param: [0.1,1e-3]
rotate_degree: 30
# search
crop_size:
  - [8,128,128]
  - [16,128,128]
  - [32,128,128]
  - [8,256,256]
  - [12,256,256]
  - [16,256,256]
  - [8,360,360]
  - [12,360,360]
  - [16,360,360]
  - [32,360,360]
affine_degree: [10,30]
affine_scale:
  - [0.5,1.1]
  - [1.1,1.5]
  - [1.5,2]
affine_shears: [10,20]
mask: null

# retrain
# crop_size:
#   - [16,128,128]
#   - [32,128,128]
#   - [64,128,128]
#   - [16,180,180]
#   - [32,180,180]
#   - [64,180,180]
#   - [16,224,224]
#   - [32,224,224]
#   - [8,360,360]
#   - [16,360,360]
# search
# crop_size:
#   - [16,32,32]
#   - [32,32,32]
#   - [64,32,32]
#   - [16,64,64]
#   - [32,64,64]
#   - [64,64,64]
#   - [8,96,96]
#   - [16,96,96]
#   - [32,96,96]
#   - [64,96,96]